#!/usr/bin/with-contenv bash

echo "**** installing pyenv ****"
if [ -d "$HOME/.pyenv/" ]; 
then 
    echo "pyenv already installed" 
else
    curl https://pyenv.run | bash
fi

if [ -f "$HOME/.zshrc" ]; 
then
    echo "**** .zshrc Found ****"
    isInFile=$(cat $HOME/.zshrc | grep -c ".pyenv")
    if [ $isInFile -eq 0 ]; 
    then
        echo "**** Adding pyenv to PATH ****"
        echo '# Adding pyenv to PATH' >> $HOME/.zshrc
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.zshrc
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.zshrc
        echo 'if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi' >> $HOME/.zshrc
    else
        echo "pyenv already on zshrc PATH"
    fi
else
    echo ".zshrc not present"
fi

if [ -f "$HOME/.bashrc" ]; 
then
    echo "**** .bashrc Found ****"
    isInFile=$(cat $HOME/.bashrc | grep -c ".pyenv")
    if [ $isInFile -eq 0 ]; 
    then
        echo "**** Adding pyenv to PATH ****"
        echo '# Adding pyenv to PATH' >> $HOME/.bashrc
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bashrc
        echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> $HOME/.bashrc
        echo 'if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi' >> $HOME/.bashrc
    else
        echo "pyenv already on bashrc PATH"
    fi
else
    echo ".bashrc not present"
fi
